spring:
  application:
    name: san-isidro-restaurant

  datasource:
    url: jdbc:postgresql://localhost:5432/san_isidro
    username: postgres
    password: TheKing
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:N8sH0LkP7C9y4q1F2B3X6vTj8dW+zR5YhK0pUgQeMnAoIsJcZxVbTfLrGw==}
    access-token-expiration: 3600000       # 1 hora
    refresh-token-expiration: 1209600000   # 14 dias